/* Level 2031 — V7 Core Engine
   Local-first life RPG foundation. Versioned state, ledgers, daily missions, stats, finance, HVAC, trading, fitness, faith, goals, achievements, backup/restore.
*/
const KEY='level2031';
const SCHEMA=7;
const TIERS={easy:50,medium:150,hard:400,epic:1000};
const baseState={schemaVersion:SCHEMA,profile:{name:'',city:'',startDate:''},xp:0,credits:0,level:1,streak:0,lastDay:'',theme:'dark',daily:{date:'',time:'',missions:[],bonus:[],status:'yellow',morning:false,evening:false,coreBonus:false,epicBonus:false},goals:{investmentsTarget:500000,emergencyTarget:50000,hvacIncomeTarget:250000,tradingWeeklyTarget:2000,companyRevenueTarget:5000000},stats:{investments:0,emergency:0,hvacIncome:0,hvacInstalls:0,hvacSales:0,tradingProfit:0,workouts:0,bibleChapters:0,books:0,trips:0,netWorth:0},finance:{accounts:[],assets:[],liabilities:[],transactions:[]},hvac:{jobs:[],payments:[]},trading:{trades:[]},fitness:{workouts:[]},faith:{entries:[]},development:{entries:[]},relationships:{entries:[]},travel:{entries:[]},vehicles:{entries:[]},lifeLog:[],xpLedger:[],creditLedger:[],achievements:[],inventory:[],audit:[]};
const clone=x=>JSON.parse(JSON.stringify(x));
function merge(raw){const r=raw&&typeof raw==='object'?raw:{};const s=clone(baseState);Object.keys(s).forEach(k=>{if(r[k]!==undefined)s[k]=r[k]});s.schemaVersion=SCHEMA;s.goals={...baseState.goals,...(r.goals||{})};s.stats={...baseState.stats,...(r.stats||{})};s.daily={...baseState.daily,...(r.daily||{})};['finance','hvac','trading','fitness','faith','development','relationships','travel','vehicles'].forEach(k=>s[k]={...baseState[k],...(r[k]||{})});return s}
let s;try{s=merge(JSON.parse(localStorage.getItem(KEY)||'null'))}catch(e){s=clone(baseState)}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localTime(){return new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function daysBetween(a,b){return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function levelFor(x){return Math.floor(Math.sqrt(Math.max(0,x)/250))+1}
function xpIntoLevel(){const l=levelFor(s.xp);const floor=250*(l-1)*(l-1);const ceil=250*l*l;return Math.max(0,Math.min(100,(s.xp-floor)/(ceil-floor)*100))}
function ledger(type,amount,reason,meta={}){const item={id:crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random(),date:localDate(),amount,reason,meta};if(type==='xp')s.xpLedger.push(item);else s.creditLedger.push(item);}
function awardXP(amount,reason,meta={}){if(!amount)return;s.xp+=Math.max(0,amount);ledger('xp',Math.max(0,amount),reason,meta);const old=s.level;s.level=levelFor(s.xp);if(s.level>old)toast(`LEVEL UP • ${s.level}`);save()}
function awardCredits(amount,reason,meta={}){if(!amount)return;s.credits+=Math.max(0,amount);ledger('credits',Math.max(0,amount),reason,meta);save()}
function toast(t){const e=document.querySelector('.toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>e.style.display='none',2200)}
function audit(action,data={}){s.audit.push({date:new Date().toISOString(),action,data});if(s.audit.length>1000)s.audit=s.audit.slice(-1000)}
function netWorth(){const accounts=s.finance.accounts.reduce((a,x)=>a+Number(x.balance||0),0),assets=s.finance.assets.reduce((a,x)=>a+Number(x.value||0),0),debts=s.finance.liabilities.reduce((a,x)=>a+Number(x.balance||0),0);return accounts+assets-debts}
function recalc(){s.stats.investments=s.finance.accounts.filter(a=>a.type==='investment').reduce((a,x)=>a+Number(x.balance||0),0);s.stats.emergency=s.finance.accounts.filter(a=>a.type==='emergency').reduce((a,x)=>a+Number(x.balance||0),0);s.stats.netWorth=netWorth();s.stats.hvacIncome=s.hvac.payments.reduce((a,x)=>a+Number(x.amount||0),0);s.stats.hvacInstalls=s.hvac.jobs.filter(x=>x.type==='install').length;s.stats.hvacSales=s.hvac.jobs.filter(x=>x.type==='sale').length;s.stats.tradingProfit=s.trading.trades.reduce((a,x)=>a+Number(x.pnl||0),0);s.stats.workouts=s.fitness.workouts.length;s.stats.bibleChapters=s.faith.entries.filter(x=>x.kind==='bible').reduce((a,x)=>a+Number(x.amount||0),0);s.stats.books=s.development.entries.filter(x=>x.kind==='book').length;s.stats.trips=s.travel.entries.length}
function missionCatalog(time){const all=[
 {id:'bible',t:'Read 1 chapter of the Bible',m:15,x:75,cat:'Faith'},
 {id:'run',t:'Run or walk for 15 minutes',m:15,x:75,cat:'Fitness'},
 {id:'priorities',t:'Review today’s top 3 priorities',m:10,x:50,cat:'Planning'},
 {id:'finance',t:'Review your financial dashboard',m:15,x:75,cat:'Finance'},
 {id:'hvac',t:'Study HVAC technical material',m:30,x:150,cat:'HVAC'},
 {id:'trade',t:'Review trading journal and risk plan',m:15,x:75,cat:'Trading'},
 {id:'dev',t:'Practice a personal-development skill',m:30,x:150,cat:'Growth'},
 {id:'gym',t:'Complete a focused gym session',m:60,x:400,cat:'Fitness'},
 {id:'family',t:'Make intentional time for your relationships',m:30,x:150,cat:'Relationships'}];
 const n={'15 min':2,'30 min':3,'1 hr':4,'2 hrs':6,'3+ hrs':7}[time]||3;return all.slice(0,n).map((m,i)=>({...m,key:m.id+'-'+localDate(),done:false,progress:0,required:m.m}));
}
function ensureDaily(){const d=localDate();if(s.daily.date!==d){if(s.daily.date){const prev=s.daily;const done=prev.missions.filter(m=>m.done).length;const total=prev.missions.length;const status=done===0?'red':done<total?'yellow':'green';prev.status=status;if(status==='red')s.streak=0;else s.streak+=1;}
 s.daily={date:d,time:'',missions:[],bonus:[],status:'yellow',morning:false,evening:false,coreBonus:false,epicBonus:false};audit('new_day',{date:d});save()}}
function setTime(t){ensureDaily();s.daily.time=t;s.daily.missions=missionCatalog(t);s.daily.bonus=[];save();render('missions');toast(`Mission load set to ${t}`)}
function completeMission(i,partial=null){ensureDaily();const m=s.daily.missions[i];if(!m||m.done)return;const pct=partial===null?100:Math.max(0,Math.min(100,Number(partial)));m.progress=pct;if(pct<100){const xp=Math.round(m.x*pct/100);if(xp)awardXP(xp,`Partial mission: ${m.t}`,{mission:m.id,percent:pct});toast(`${pct}% complete • +${Math.round(m.x*pct/100)} XP`);save();return}m.done=true;m.progress=100;awardXP(m.x,`Mission: ${m.t}`,{mission:m.id});awardCredits(10,`Mission: ${m.t}`,{mission:m.id});if(m.id==='bible')s.faith.entries.push({date:localDate(),kind:'bible',amount:1,note:'Mission'});if(m.id==='run'||m.id==='gym')s.fitness.workouts.push({date:localDate(),kind:m.id,duration:m.m,note:'Mission'});audit('mission_complete',{id:m.id});checkDailyBonuses();recalc();save();render('missions');toast(`Mission complete • +${m.x} XP • +10 credits`)}
function checkDailyBonuses(){const ms=s.daily.missions,done=ms.length&&ms.every(m=>m.done);if(done&&!s.daily.coreBonus){s.daily.coreBonus=true;awardXP(100,'Core Day bonus');awardCredits(25,'Core Day bonus');s.achievements.push({id:'core-'+localDate(),name:'Core Day',rarity:'uncommon',date:localDate(),xp:100});}if(done&&s.daily.bonus.length===0){s.daily.bonus=[{id:'bonus-life',t:'Log one meaningful real-world accomplishment',m:15,x:75,cat:'Life',key:'bonus-'+localDate(),done:false,progress:0,required:15},{id:'bonus-review',t:'Write a 5-minute end-of-day reflection',m:15,x:75,cat:'Life',key:'bonus2-'+localDate(),done:false,progress:0,required:15}];save()}}
function completeBonus(i){const m=s.daily.bonus[i];if(!m||m.done)return;m.done=true;m.progress=100;awardXP(m.x,`Bonus mission: ${m.t}`);awardCredits(10,`Bonus mission: ${m.t}`);if(s.daily.bonus.every(x=>x.done)&&!s.daily.epicBonus){s.daily.epicBonus=true;awardXP(1000,'Epic Day');awardCredits(100,'Epic Day');s.achievements.push({id:'epic-'+localDate(),name:'Epic Day',rarity:'epic',date:localDate(),xp:1000});toast('EPIC DAY UNLOCKED • +1,000 XP');}save();render('missions')}
function status(){const m=s.daily.missions;if(!m.length)return'not-set';const d=m.filter(x=>x.done).length;return d===m.length?'green':d===0?'red':'yellow'}
function pct(v,target){return Math.min(100,Math.max(0,(Number(v)||0)/target*100))}
function home(){recalc();const l=levelFor(s.xp);return `<div class="hero"><div class="future">SEPTEMBER 2031 • FUTURE WORLD</div><h1>Now build it.</h1><p>Your real life is the game. Level 2031 turns verified progress into XP, achievements and a changing world.</p><div class="heroStats"><span class="pill">LEVEL ${l}</span><span class="pill">${s.streak} DAY STREAK</span><span class="pill">${s.credits.toLocaleString()} CREDITS</span></div></div><div class="grid"><div class="card"><div class="label">TOTAL XP</div><div class="big gold">${s.xp.toLocaleString()}</div><div class="xpbar"><div class="xpfill" style="width:${xpIntoLevel()}%"></div></div><small>${Math.round(xpIntoLevel())}% to next level</small></div><div class="card"><div class="label">NET WORTH</div><div class="big">${money(s.stats.netWorth)}</div><small>Assets + cash − liabilities</small></div><div class="card"><div class="label">INVESTMENTS</div><div class="big">${money(s.stats.investments)}</div><small>Goal ${money(s.goals.investmentsTarget)}</small></div><div class="card"><div class="label">EMERGENCY FUND</div><div class="big">${money(s.stats.emergency)}</div><small>Goal ${money(s.goals.emergencyTarget)}</small></div></div><div class="section"><div class="row"><h2>2031 Targets</h2><button class="btn ghost" onclick="render('goals')">Open goals</button></div>${goal('Control AC & Heat',money(s.goals.companyRevenueTarget)+' annual company revenue',0)}${goal('Personal HVAC',money(s.goals.hvacIncomeTarget)+' after-tax income',pct(s.stats.hvacIncome,s.goals.hvacIncomeTarget))}${goal('Investments',money(s.goals.investmentsTarget)+' invested',pct(s.stats.investments,s.goals.investmentsTarget))}${goal('Emergency Fund',money(s.goals.emergencyTarget)+' cash reserve',pct(s.stats.emergency,s.goals.emergencyTarget))}${goal('Trading',money(s.goals.tradingWeeklyTarget)+'/week target',0)}</div>`}
function goal(a,b,p){return `<div class="card goal"><div class="row"><b>${esc(a)}</b><span class="pill">2031</span></div><div class="label">${esc(b)}</div><div class="statline"><i style="width:${Math.min(100,p)}%"></i></div></div>`}
function missions(){ensureDaily();const d=s.daily;return `<div class="section"><div class="row"><div><div class="label">${localDate()}</div><h1>Mission Briefing</h1></div><span class="pill ${status()}" >${status().toUpperCase()}</span></div><div class="card"><div class="label">MORNING CHECK-IN</div><p>How much focused time do you have today?</p><div class="timegrid">${['15 min','30 min','1 hr','2 hrs','3+ hrs'].map(t=>`<button class="time ${d.time===t?'selected':''}" onclick="setTime('${t}')">${t}</button>`).join('')}</div><button class="btn" onclick="morningCheckin()">${d.morning?'✓ Morning check-in complete':'Complete morning check-in'}</button></div>${d.missions.length?`<div class="section"><div class="row"><h2>Core Missions</h2><span class="pill">${d.missions.filter(m=>m.done).length}/${d.missions.length}</span></div>${d.missions.map((m,i)=>missionCard(m,`completeMission(${i})`)).join('')}</div>`:'<div class="card empty">Choose your available time to generate today’s missions.</div>'}${d.bonus.length?`<div class="section"><h2>Bonus Missions</h2>${d.bonus.map((m,i)=>missionCard(m,`completeBonus(${i})`)).join('')}</div>`:''}<div class="card"><div class="row"><b>Evening debrief</b><span class="pill">${d.evening?'DONE':'PENDING'}</span></div><p class="label">Finish the day with a simple report. Your daily status is based on actual completion.</p><button class="btn ghost" onclick="eveningCheckin()">${d.evening?'Review debrief':'Complete evening debrief'}</button></div></div>`}
function missionCard(m,fn){return `<div class="mission ${m.done?'done':''}" onclick="${fn}"><div class="check">${m.done?'✓':''}</div><div style="flex:1"><b>${esc(m.t)}</b><small>${m.m} min • ${m.x} XP • ${esc(m.cat)}</small>${m.progress&&m.progress<100?`<div class="statline"><i style="width:${m.progress}%"></i></div>`:''}</div><span class="pill">${m.done?'DONE':'+'+m.x+' XP'}</span></div>`}
function morningCheckin(){ensureDaily();s.daily.morning=true;save();toast('Morning check-in complete');render('missions')}
function eveningCheckin(){ensureDaily();const st=status();s.daily.status=st;s.daily.evening=true;if(st==='red')s.streak=0;else if(st==='green'||st==='yellow')s.streak=Math.max(1,s.streak);audit('evening_checkin',{status:st});save();toast(`Day closed • ${st.toUpperCase()}`);render('missions')}
function stats(){recalc();const q=s.stats;const cards={"Net Worth":money(q.netWorth),Investments:money(q.investments),'Emergency Fund':money(q.emergency),'HVAC Income':money(q.hvacIncome),'HVAC Installs':q.hvacInstalls,'Systems Sold':q.hvacSales,'Trading Profit':money(q.tradingProfit),Workouts:q.workouts,'Bible Chapters':q.bibleChapters,Books:q.books,Trips:q.trips,'Life Events':s.lifeLog.length,'Achievements':s.achievements.length};return `<div class="section"><div class="label">LIFETIME CHARACTER STATS</div><h1>Stats</h1><div class="grid">${Object.entries(cards).map(([k,v])=>`<div class="card"><div class="label">${k}</div><div class="big">${v}</div></div>`).join('')}</div><div class="section"><div class="card"><div class="row"><b>XP ledger</b><span>${s.xpLedger.length} entries</span></div><div class="ledger">${s.xpLedger.slice(-8).reverse().map(x=>`<div><span>${esc(x.reason)}</span><b>+${x.amount} XP</b></div>`).join('')||'<span class="label">No XP history yet.</span>'}</div></div></div></div>`}
function goals(){return `<div class="section"><div class="label">CAMPAIGN</div><h1>2031 Goals</h1>${goal('Control AC & Heat',money(s.goals.companyRevenueTarget)+' annual company revenue',0)}${goal('Personal HVAC',money(s.goals.hvacIncomeTarget)+' after-tax income',pct(s.stats.hvacIncome,s.goals.hvacIncomeTarget))}${goal('Investments',money(s.goals.investmentsTarget)+' invested',pct(s.stats.investments,s.goals.investmentsTarget))}${goal('Emergency Fund',money(s.goals.emergencyTarget)+' separate cash',pct(s.stats.emergency,s.goals.emergencyTarget))}${goal('Trading',money(s.goals.tradingWeeklyTarget)+' weekly target',0)}<div class="card"><b>Source of truth</b><p class="label">Your five-year goals remain the campaign target. V7 tracks verified progress rather than inventing progress.</p></div></div>`}
function finance(){recalc();return `<div class="section"><div class="row"><div><div class="label">FINANCIAL ENGINE</div><h1>Money</h1></div><button class="btn" onclick="addAccount()">+ Account</button></div><div class="grid"><div class="card"><div class="label">NET WORTH</div><div class="big">${money(s.stats.netWorth)}</div></div><div class="card"><div class="label">INVESTMENTS</div><div class="big">${money(s.stats.investments)}</div></div><div class="card"><div class="label">EMERGENCY</div><div class="big">${money(s.stats.emergency)}</div></div><div class="card"><div class="label">LIABILITIES</div><div class="big">${money(s.finance.liabilities.reduce((a,x)=>a+Number(x.balance||0),0))}</div></div></div><div class="section"><h2>Accounts</h2>${s.finance.accounts.map((a,i)=>`<div class="card row"><div><b>${esc(a.name)}</b><div class="label">${esc(a.type)}</div></div><div class="right"><b>${money(a.balance)}</b><button class="mini" onclick="deleteAccount(${i})">×</button></div></div>`).join('')||'<div class="empty">Add your real accounts. Net worth is calculated from them.</div>'}</div><div class="section"><div class="row"><h2>Assets & debts</h2><button class="btn ghost" onclick="addAssetDebt()">+ Entry</button></div>${[...s.finance.assets.map((a,i)=>`<div class="card row"><span>${esc(a.name)} <small>asset</small></span><b>${money(a.value)}</b></div>`),...s.finance.liabilities.map(a=>`<div class="card row"><span>${esc(a.name)} <small>debt</small></span><b>-${money(a.balance)}</b></div>`)].join('')||'<div class="empty">Add vehicles, real estate, loans, credit cards, or other balance-sheet items.</div>'}</div><div class="card"><b>Two-week financial check-in</b><p class="label">V7 records the last check-in and keeps it visible. Background reminders can be added later with push infrastructure.</p><button class="btn ghost" onclick="financialCheckin()">Complete check-in</button></div></div>`}
function addAccount(){const name=prompt('Account name');if(!name)return;const type=prompt('Type: cash, emergency, investment, checking, savings','checking')||'checking';const balance=Number(prompt('Current balance','0')||0);s.finance.accounts.push({name,type,balance});audit('account_added',{name,type});recalc();save();render('finance')}
function deleteAccount(i){if(!confirm('Remove this account from Level 2031?'))return;s.finance.accounts.splice(i,1);recalc();save();render('finance')}
function addAssetDebt(){const isDebt=confirm('Is this a debt/liability? OK = debt, Cancel = asset');const name=prompt(isDebt?'Debt name':'Asset name');if(!name)return;const value=Number(prompt('Current value/balance','0')||0);if(isDebt)s.finance.liabilities.push({name,balance:value});else s.finance.assets.push({name,value});recalc();save();render('finance')}
function financialCheckin(){s.audit.push({date:new Date().toISOString(),action:'financial_checkin'});save();toast('Financial check-in recorded')}
function hvac(){return `<div class="section"><div class="row"><div><div class="label">CONTROL AC & HEAT</div><h1>HVAC</h1></div><button class="btn" onclick="addHVAC()">+ Job</button></div><div class="grid"><div class="card"><div class="label">PERSONAL HVAC INCOME</div><div class="big">${money(s.stats.hvacIncome)}</div></div><div class="card"><div class="label">INSTALLS</div><div class="big">${s.stats.hvacInstalls}</div></div><div class="card"><div class="label">SALES</div><div class="big">${s.stats.hvacSales}</div></div></div><div class="section"><h2>Jobs</h2>${s.hvac.jobs.slice().reverse().map(j=>`<div class="card"><div class="row"><b>${esc(j.type)}</b><span class="pill">${j.date}</span></div><div class="label">${esc(j.note||'')}</div></div>`).join('')||'<div class="empty">Log sales and installs as they happen. Add-ons are tracked without XP.</div>'}</div><div class="section"><h2>Payments</h2>${s.hvac.payments.slice().reverse().map(p=>`<div class="card row"><span>${p.date} • ${esc(p.note||'Payment')}</span><b>${money(p.amount)}</b></div>`).join('')||'<div class="empty">Log each personal HVAC payment.</div>'}</div></div>`}
function addHVAC(){const type=prompt('Enter: sale, install, or payment','install');if(!type)return;if(type==='payment'){const amount=Number(prompt('Payment amount','0')||0);if(amount>0)s.hvac.payments.push({date:localDate(),amount,note:'Personal HVAC payment'});}else{s.hvac.jobs.push({date:localDate(),type:type==='sale'?'sale':'install',note:prompt('Optional job note')||''});awardXP(type==='install'?100:100,`HVAC ${type}`,{type});awardCredits(10,`HVAC ${type}`,{type});}recalc();save();render('hvac')}
function trading(){const profit=s.stats.tradingProfit;return `<div class="section"><div class="row"><div><div class="label">TRADING JOURNAL</div><h1>Trading</h1></div><button class="btn" onclick="addTrade()">+ Trade</button></div><div class="grid"><div class="card"><div class="label">LIFETIME P&L</div><div class="big">${money(profit)}</div></div><div class="card"><div class="label">TRADES</div><div class="big">${s.trading.trades.length}</div></div><div class="card"><div class="label">WIN RATE</div><div class="big">${s.trading.trades.length?Math.round(s.trading.trades.filter(t=>t.pnl>0).length/s.trading.trades.length*100):0}%</div></div></div><div class="section">${s.trading.trades.slice().reverse().map(t=>`<div class="card"><div class="row"><b>${esc(t.symbol)}</b><span class="pill">${t.date}</span></div><div class="row"><span>${esc(t.setup||'')}</span><b class="${t.pnl>=0?'positive':'negative'}">${t.pnl>=0?'+':''}${money(t.pnl)}</b></div></div>`).join('')||'<div class="empty">Every trade belongs in the journal. Profitable trades earn XP; losses do not.</div>'}</div></div>`}
function addTrade(){const symbol=prompt('Symbol','MNQ');if(!symbol)return;const pnl=Number(prompt('P&L (negative for loss)','0')||0);const setup=prompt('Setup / note')||'';s.trading.trades.push({date:localDate(),symbol,pnl,setup});if(pnl>0){awardXP(Math.min(250,Math.max(25,Math.round(pnl/10))),`Profitable trade: ${symbol}`,{pnl});awardCredits(5,'Profitable trade');}recalc();save();render('trading')}
function simpleModule(title,kind,arr,label){return `<div class="section"><div class="row"><div><div class="label">${esc(label||kind.toUpperCase())}</div><h1>${esc(title)}</h1></div><button class="btn" onclick="addSimple('${kind}')">+ Log</button></div>${arr.slice().reverse().map(e=>`<div class="card"><div class="row"><b>${esc(e.kind||e.title||kind)}</b><span class="pill">${esc(e.date)}</span></div><div class="label">${esc(e.note||'')}</div></div>`).join('')||'<div class="empty">Start the lifetime record here.</div>'}</div>`}
function fitness(){return simpleModule('Fitness','fitness',s.fitness.workouts,'FITNESS TRACKER')}
function faith(){return simpleModule('Faith','faith',s.faith.entries,'FAITH TRACKER')}
function development(){return simpleModule('Personal Development','development',s.development.entries,'GROWTH TRACKER')}
function addSimple(kind){const note=prompt('What did you do?');if(!note)return;let item={date:localDate(),kind,note};if(kind==='faith'){const amount=Number(prompt('Amount (chapters/units)','1')||1);item={...item,kind:'bible',amount};awardXP(50,'Faith action');awardCredits(5,'Faith action');}else if(kind==='fitness'){awardXP(100,'Fitness action');awardCredits(10,'Fitness action');}else{awardXP(50,'Personal development action');awardCredits(5,'Personal development action');}s[kind].entries?s[kind].entries.push(item):s[kind].workouts.push(item);recalc();save();render(kind==='fitness'?'fitness':kind==='faith'?'faith':'development')}
function achievements(){return `<div class="section"><div class="label">COLLECTION</div><h1>Achievements</h1>${s.achievements.slice().reverse().map(a=>`<div class="card"><div class="row"><b>${esc(a.name)}</b><span class="pill">${esc(a.rarity||'uncommon')}</span></div><div class="label">${a.date} • +${a.xp||0} XP</div></div>`).join('')||'<div class="empty">Your first achievement is waiting.</div>'}</div>`}
function log(){return `<div class="section"><div class="row"><div><div class="label">LIFE LOG</div><h1>Timeline</h1></div><button class="btn" onclick="addEvent()">+ Log</button></div>${s.lifeLog.slice().reverse().map(e=>`<div class="card"><div class="row"><b>${esc(e.title)}</b><span class="pill">${e.date}</span></div><div class="label">${esc(e.note||'')}</div></div>`).join('')||'<div class="empty">Your life history starts here.</div>'}</div>`}
function addEvent(){const title=prompt('What happened?');if(!title)return;const note=prompt('Optional note')||'';s.lifeLog.push({date:localDate(),title,note});save();render('log')}
function backup(){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`level2031-backup-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{s=merge(JSON.parse(r.result));recalc();save();render('home');toast('Backup restored')}catch(e){alert('Invalid Level 2031 backup.')}};r.readAsText(f)};input.click()}
function resetApp(){if(!confirm('This deletes the local Level 2031 save. Export a backup first. Continue?'))return;localStorage.removeItem(KEY);location.reload()}
function more(){render('more')}
function moreView(){return `<div class="section"><div class="label">SYSTEM</div><h1>More</h1><div class="card"><b>Level 2031 V7 Core Engine</b><p class="label">Schema ${SCHEMA} • Local-first • Privacy-first</p></div><div class="grid"><button class="card action" onclick="backup()">⬇ Backup data</button><button class="card action" onclick="restore()">⬆ Restore backup</button><button class="card action" onclick="toggleTheme()">◐ Toggle theme</button><button class="card action" onclick="resetApp()">Reset local save</button></div><div class="section"><h2>Current systems</h2><div class="card"><p class="label">✓ Versioned state & migration<br>✓ XP + credit ledgers<br>✓ Time-based mission engine<br>✓ Partial completion<br>✓ Daily status & streak foundation<br>✓ Core Day + Epic Day<br>✓ Derived net worth<br>✓ Finance accounts/assets/liabilities<br>✓ HVAC job & payment tracking<br>✓ Trading journal<br>✓ Fitness / faith / development logs<br>✓ Achievements<br>✓ Life Log<br>✓ Backup / restore</p></div></div></div>`}
function toggleTheme(){s.theme=s.theme==='light'?'dark':'light';save();render(currentView)}
let currentView='home';
function render(view='home'){currentView=view;ensureDaily();document.body.className=s.theme==='light'?'light':'';const content=view==='home'?home():view==='missions'?missions():view==='stats'?stats():view==='goals'?goals():view==='finance'?finance():view==='hvac'?hvac():view==='trading'?trading():view==='fitness'?fitness():view==='faith'?faith():view==='development'?development():view==='achievements'?achievements():view==='log'?log():moreView();const nav=[['home','⌂','Home'],['missions','⚔','Missions'],['stats','◈','Stats'],['log','✦','Life Log'],['more','☰','More']];document.getElementById('app').innerHTML=`<div class="shell"><header class="top"><div><div class="brand">LEVEL 2031</div><div class="level">${localDate()} • ${localTime()} • LEVEL ${levelFor(s.xp)}</div></div><button class="themeBtn" onclick="toggleTheme()">${s.theme==='dark'?'☼':'☾'}</button></header><main class="content">${content}</main><div class="toast"></div><nav class="nav"><div class="navin">${nav.map(([v,i,t])=>`<button class="${view===v?'active':''}" onclick="render('${v}')"><span>${i}</span>${t}</button>`).join('')}</div></nav></div>`}
ensureDaily();recalc();save();render('home');
